const dataProducts = `[
    {
        "id" : "1",
        "picture" : "img/prod1.png",
        "picture_class" : ["product_img"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod1.png",
        "vector" : "./img/vector.svg"
    },
    {
        "id" : "2",
        "picture" : "img/prod2.svg",
        "picture_class" : ["product_img", "product_img2"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod2.svg",
        "vector" : "./img/vector.svg"
    },
    {
        "id" : "3",
        "picture" : "img/prod3.png",
        "picture_class" : ["product_img"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod3.png",
        "vector" : "./img/vector.svg"
    },
    {
        "id" : "4",
        "picture" : "img/prod4.png",
        "picture_class" : ["product_img"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod4.png",
        "vector" : "./img/vector.svg"
    },
    {
        "id" : "5",
        "picture" : "img/prod5.png",
        "picture_class" : ["product_img"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod5.png",
        "vector" : "./img/vector.svg"
    },
    {
        "id" : "6",
        "picture" : "img/prod6.png",
        "picture_class" : ["product_img"],
        "brand" : "ELLERY X M'O CAPSULE", 
        "description":"Known for her sculptural takes ontraditional tailoring, Australian arbiter ofcool Kym Ellery teams upwith Moda Operandi.",
        "price" : "52.00",
        "currency":"$",
        "brand" : "MANGO  PEOPLE",
        "category" : "T-SHIRT",
        "Price" : "300",
        "Currency" : "$",
        "Color" : "Red",
        "Size" : "Xl",
        "Quantity" : "2",
        "img" : "./img/prod6.png",
        "vector" : "./img/vector.svg"
    }
]`